services:
  disco-web:
    image: norrbey/disco-web:latest
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings:DefaultConnection=Data Source=/app/Db/disco_storage.db
      - Discord:BotToken=your-token
      - JWT:Secret=your-secret
      - JWT:PasswordHash=your-password
